ALTER TABLE trades ADD COLUMN IF NOT EXISTS trade_date_time TIMESTAMP;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS image_url1 VARCHAR(255);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS image_url2 VARCHAR(255);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS image_url3 VARCHAR(255);