ALTER TABLE trades ALTER COLUMN image_url1 TYPE TEXT;
ALTER TABLE trades ALTER COLUMN image_url2 TYPE TEXT;
ALTER TABLE trades ALTER COLUMN image_url3 TYPE TEXT;
ALTER TABLE trades ALTER COLUMN notes TYPE TEXT;